name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate-composer:
    name: "Validate dependency installation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        extensions: [ "scoutapm", "" ]
        laravel-version:
          - "5.5.*"
          - "6.*"
          - "7.*"
          - "8.*"
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
        exclude:
          - { php-version: "7.1", laravel-version: "6.*" } # Laravel 6 requires 7.2+
          - { php-version: "7.1", laravel-version: "7.*" } # Laravel 7 requires 7.2+
          - { php-version: "7.1", laravel-version: "8.*" } # Laravel 8 requires 7.3+
          - { php-version: "7.2", laravel-version: "8.*" } # Laravel 8 requires 7.3+
    steps:
      - uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl
          extensions: ${{ matrix.extensions }}
      # --no-update then a full `composer update` is needed to overcome locked dependencies
      # See: https://github.com/composer/composer/issues/9561
      - name: "Require specific Laravel version ${{ matrix.laravel-version}}"
        run: "composer require laravel/framework:${{ matrix.laravel-version}} --no-update --no-interaction --prefer-dist --prefer-stable"
      - name: "Composer update with new requirements"
        run: "composer update --no-interaction --prefer-dist --prefer-stable"
